### ISSUE TITLE
SOS

### ISSUE THREAD

**Issue by sam920829** [Sobhan-SRZA/Moderation-Bot#1]
SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Users\user\Downloads\Moderation-Bot-main\Moderatio
n-Bot-main\node_modules\discord-giveaways\index.js:3:23)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)

**Comment by Sobhan-SRZA** [comment]
you need delete a package-lock.json and send a this command in your terminal: npm install
if you’ve got an error report it for me
